### ISSUE TITLE
Add support for interactive docs to PyData Sphinx

### ISSUE THREAD

**Issue by trallard** [Quansight-Labs/czi-scientific-python-mgmt#15]
## 📝 Summary

Add support and new features to support interactive documentation examples in the PyData Sphinx theme.

## 🚀 Tasks / Deliverables

TBD

## 📅 Estimated completion

[12 months milestone](https://github.com/Quansight-Labs/czi-scientific-python-mgmt/milestone/1)

## 📋 Additional information

-

**Comment by rgommers** [comment]
This was done via the "Try examples" functionality that @steppi added to `jupyterlite-sphinx`: https://jupyterlite-sphinx.readthedocs.io/en/latest/directives/try_examples.html. See also https://github.com/scipy/scipy/issues/19729 for more context.

This may be further polished in the course of rolling out interactive docs and getting user feedback. However, we can consider this goal achieved I'd say.
