### ISSUE TITLE
Add interactive documentation examples to at least one project

### ISSUE THREAD

**Issue by trallard** [Quansight-Labs/czi-scientific-python-mgmt#16]
## 📝 Summary

Make all the examples in the API reference guide and tutorials of at least 1 project interactive via JupyterLite or PyScript (available to end users).

## 🚀 Tasks / Deliverables

TBD			

## 📅 Estimated completion

[12 months milestone](https://github.com/Quansight-Labs/czi-scientific-python-mgmt/milestone/1)

## 📋 Additional information

-

**Comment by rgommers** [comment]
An experimental deployment was done by @steppi for SciPy, see https://github.com/scipy/scipy/issues/19729. Getting ready to do that for the 1.12.0 release which is coming out soon I believe. And then this initial goal will be met.

After that, it's on to further improvements and other projects (xref gh-19 for that year 2 goal).

**Comment by rgommers** [comment]
https://pywavelets.readthedocs.io/en/latest/ is interactive now. There's no shortage of things left to do to mature/polish everything, and deploy things for SciPy and then other projects. But let's leave that for gh-19. I'd say that this goal was met, so closing.

**Comment by rgommers** [comment]
For the record, the work consisted of:
- a lot of `jupyterlite-sphinx` improvements & feature releases
- adding CI jobs for Emscripten/Pyodide and ensuring that the test suite passes with it
- documentation improvements in the project, modernizing everything etc.. `Examples` in the API reference work automatically, other code examples in narrative code needed custom directives like `.. try-exampes::`

Nightly `wasm32` wheels are also being produced and uploaded to https://anaconda.org/scientific-python-nightly-wheels/. Those should still be pulled in though (right now the `pywavelets` inside Pyodide is used); an issue with CORS headers needs resolving on the anaconda.org index to make that work with Pyodide's `micropip`.
