### ISSUE TITLE
Buttons meet criteria

### ISSUE THREAD

**Issue by trallard** [Quansight-Labs/czi-scientific-python-mgmt#36]

**Comment by smeragoel** [comment]
Figma link: https://www.figma.com/file/BHkBFxg1Qg0h5RApUw1ZrR/PyData-Design-system---Ongoing?type=design&node-id=2550%3A1419&mode=design&t=mVsE9aEb6MYisS7W-1

**Comment by trallard** [comment]
@smeragoel to check the "Scroll to top" button
