### ISSUE TITLE
a11y weekly sync - 19/09/2023

### ISSUE THREAD

**Issue by trallard** [Quansight-Labs/czi-scientific-python-mgmt#42]
## Discussion notes

Follow-up on buttons issues:

@gabalafou:
- [x] Ping on PR review https://github.com/executablebooks/sphinx-design/pull/158 
- [x] Need to update PST docs: disclaimer about buttons and when to use them
- Tangential: Hide search should be a button (this changes state) - do NOT add a button component that we have to maintain
- [x] Discussed https://github.com/pydata/pydata-sphinx-theme/pull/1459 - discussed three options alt+text, text only, neither
- [x] will continue to work on https://github.com/pydata/pydata-sphinx-theme/issues/1428

@smeragoel 
- [x] Will work on navbar focus states

Audit: https://github.com/Quansight-Labs/czi-scientific-python-mgmt/issues/41
- Agreed to run through the Accessibility insights https://accessibilityinsights.io/docs/web/getstarted/assessment/
- After our first audit session (this week), we will open a parallel issue on PST

**Comment by gabalafou** [comment]
I don't see it in the notes here but I thought we said in this sync that @trallard would take care of https://github.com/Quansight-Labs/accessible-pygments/issues/30, so I just now went ahead and unassigned myself from that task and assigned @trallard instead
