### ISSUE TITLE
Improve PyData libraries table styling

### ISSUE THREAD

**Issue by trallard** [Quansight-Labs/czi-scientific-python-mgmt#50]
## Summary

We have identified that the PyData tables styles need improving in the dark theme (and probably in the light theme too)

See https://pydata-sphinx-theme.readthedocs.io/en/latest/examples/pydata.html

**Comment by smeragoel** [comment]
Here are the updated designs in light and dark mode:

![image](https://github.com/Quansight-Labs/czi-scientific-python-mgmt/assets/98317216/8557ad33-86bd-45cf-9167-4735b0fa5aee)

And a preview of the interactions (hover):

https://github.com/Quansight-Labs/czi-scientific-python-mgmt/assets/98317216/3bdeb80a-d71d-4d9b-84ce-acfc73535147

Earlier, I was using the accent colour for hover but I changed it to our secondary colour purple to maintain consistency with other components. (Default = primary, hover = secondary, focus = accent)

Feedback and suggestions welcome! 🐰

**Comment by smeragoel** [comment]
I am adding some blogs / resources related to data table accessibility which might help @gabalafou 

1. https://www.a11yproject.com/posts/accessible-data-tables/#example-of-an-accessible-data-table
2. https://tink.uk/how-screen-readers-navigate-data-tables/
3. https://brucelawson.co.uk/2020/accessible-data-tables/
4. https://adrianroselli.com/2017/11/a-responsive-accessible-table.html
