### ISSUE TITLE
Links

### ISSUE THREAD

**Issue by smeragoel** [Quansight-Labs/czi-scientific-python-mgmt#61]
## 🔗 Link purpose
The purpose of a link must be described by its link text alone, or by the link text together with preceding page context - [WCAG 2.4.4](https://www.w3.org/WAI/WCAG21/Understanding/link-purpose-in-context.html)

- [ ] Instance 1
  - **Path**
    `.sd-stretched-link.external[href$="pydata.html"]`
  
  - **Snippet**
   ```html
  <a class="sd-stretched-link reference external" href="examples/pydata.html"></a>
  ```
  - **Accessible Name**
    (no value)

  - **Accessible description**
    (no value)

  - **URL**
     examples/pydata.html
     
- [ ] Instance 2
  - **Path**
    `.sd-stretched-link.external[href$="gallery.html"]`
  
  - **Snippet**
   ```html
  <a class="sd-stretched-link reference external" href="examples/gallery.html"></a>
  ```
  - **Accessible Name**
    (no value)

  - **Accessible description**
    (no value)

  - **URL**
     examples/galery.html

**Comment by gabalafou** [comment]
I think this is fixed by https://github.com/pydata/pydata-sphinx-theme/pull/1633

**Comment by gabalafou** [comment]
Closing this issue because https://github.com/pydata/pydata-sphinx-theme/pull/1633 has been merged
