### ISSUE TITLE
Landmarks

### ISSUE THREAD

**Issue by smeragoel** [Quansight-Labs/czi-scientific-python-mgmt#63]
<details>  <summary><h3>Identified landmarks screenshot</summary>
These are the landmarks identfied in the audit:

![screencapture-pydata-sphinx-theme-readthedocs-io-en-stable-2024-02-16-16_31_21](https://github.com/Quansight-Labs/czi-scientific-python-mgmt/assets/98317216/55017b2d-5a45-4de4-81fa-ffd357a31157)
</details>

 ## 1. 📍Landmark roles
Landmark roles: A landmark region must have the role that best describes its content - [WCAG 1.3.1](https://www.w3.org/WAI/WCAG21/Understanding/info-and-relationships)

```[tasklist]
### Tasks
- [x] The header has a `navigation` role, however, it might fit the `banner` role better
```

 ## 2. 📝Primary content and no repeating content
Primary content: The main landmark must contain all of the page's primary content - [WCAG 1.3.1](https://www.w3.org/WAI/WCAG21/Understanding/info-and-relationships), [WCAG 2.4.1](https://www.w3.org/WAI/WCAG21/Understanding/bypass-blocks)
No repeating content: The main landmark must not contain any blocks of content that repeat across pages - [WCAG 1.3.1](https://www.w3.org/WAI/WCAG21/Understanding/info-and-relationships), [WCAG 2.4.1](https://www.w3.org/WAI/WCAG21/Understanding/bypass-blocks)

```[tasklist]
### Tasks
- [x] There are multiple mains on the page
```

**Comment by gabalafou** [comment]
I think all of these are fixed now.

**Comment by smeragoel** [comment]
Are these fixed in pending PRs? If so, we can link them here for visibility!
