### ISSUE TITLE
Sphinx Design tabs need other hover indicator other than just color change

### ISSUE THREAD

**Issue by gabalafou** [Quansight-Labs/czi-scientific-python-mgmt#79]
Perhaps underline?

The PyData Theme docs has an [example of Sphinx Design tabs](https://pydata-sphinx-theme.readthedocs.io/en/latest/user_guide/web-components.html#tabs), where this issue can be checked.

**Comment by gabalafou** [comment]
I need design to come up with the desired interaction and then I can implement.

**Comment by smeragoel** [comment]
Here's my design proposal:

We can add a simple underline like Gabriel suggested, and it would function akin to what we have in buttons right now. 

![Image](https://github.com/Quansight-Labs/czi-scientific-python-mgmt/assets/98317216/b53714d7-a089-409c-886b-ae6c0bab4caf)

Here's a demo loom:

<div>
    <a href="https://www.loom.com/share/36706f1e817e487ba45d9b075ce51c6b">
      <p>Figma - Tabbed Interfaces (Hover) - PyData Design system - Watch Video</p>
    </a>
    <a href="https://www.loom.com/share/36706f1e817e487ba45d9b075ce51c6b">
      <img style="max-width:300px;" src="https://cdn.loom.com/sessions/thumbnails/36706f1e817e487ba45d9b075ce51c6b-with-play.gif">
    </a>
  </div>

**Comment by trallard** [comment]
Decided that an underline is good for the hover state.

**Comment by Carreau** [comment]
See https://github.com/pydata/pydata-sphinx-theme#1884
